{"name": "test_login_user_by_wrong_password", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Неверный код ответа, получен 200\nassert 200 == 400", "trace": "self = <test_api.TestWrongParameters object at 0x00000256CC296E50>, add_one_user = <api_connector.ApiConnector object at 0x00000256CC28BDF0>\n\n    @allure.feature(\"Login user into the system  /user/login\")\n    @allure.story('Выполняем вход пользователя с некорректным password')\n    @pytest.mark.login_user\n    @pytest.mark.xfail\n    def test_login_user_by_wrong_password(self, add_one_user):\n        \"\"\"logged user by correct name and wrong password\"\"\"\n        rez = add_one_user.login_user(name='test', password='1')\n        with allure.step(\"Запрос отправлен, проверяем код ответа\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 400\n\ntest_api.py:253: AssertionError"}, "description": "logged user by correct name and wrong password", "steps": [{"name": "GET request to: https://petstore.swagger.io/v2/user/login", "status": "passed", "start": 1661532018284, "stop": 1661532018284}, {"name": "Запрос отправлен, проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 253, in test_login_user_by_wrong_password\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661532018284, "stop": 1661532018284}], "start": 1661532017594, "stop": 1661532018284, "uuid": "c2049dda-0fae-4dc6-88d6-dbb63d026810", "historyId": "70ec8267b6986736e69288bcd18ecbec", "testCaseId": "bf9e83b97e26e25e0d54585efea261be", "fullName": "test_api.TestWrongParameters#test_login_user_by_wrong_password", "labels": [{"name": "feature", "value": "Login user into the system  /user/login"}, {"name": "story", "value": "Выполняем вход пользователя с некорректным password"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "login_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "16092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}