{"name": "test_login_user_by_wrong_password", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400", "trace": "self = <test_api.TestWrongParameters object at 0x000001599AE96190>, add_one_user = <api_connector.ApiConnector object at 0x000001599AF57A60>\n\n    @allure.feature(\"Login user into the system  /user/login\")\n    @allure.story('Выполняем вход пользователя с некорректным password')\n    @pytest.mark.login_user\n    def test_login_user_by_wrong_password(self, add_one_user):\n        \"\"\"logged user by correct name and wrong password\"\"\"\n        name = 'test'\n        password = '1'\n        with allure.step(f\"Выполняем вход пользователя username={name}, password={password}\"):\n            rez = add_one_user.login_user(name=name, password=password)\n        with allure.step(f\"Запрос отправлен, проверяем код ответа {rez[0]} == 400\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 400\n\ntest_api.py:303: AssertionError"}, "description": "logged user by correct name and wrong password", "steps": [{"name": "Выполняем вход пользователя username=test, password=1", "status": "passed", "steps": [{"name": "get request to: https://petstore.swagger.io/v2/user/login", "status": "passed", "start": 1661756094177, "stop": 1661756094178}], "start": 1661756093497, "stop": 1661756094178}, {"name": "Запрос отправлен, проверяем код ответа 200 == 400", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 303, in test_login_user_by_wrong_password\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661756094178, "stop": 1661756094178}], "attachments": [{"name": "log", "source": "6fe2de78-b87e-4a2e-b25a-597b0b214816-attachment.txt", "type": "text/plain"}], "start": 1661756093497, "stop": 1661756094179, "uuid": "c790558a-a2a4-42b1-8b93-29d6fb5cbc30", "historyId": "70ec8267b6986736e69288bcd18ecbec", "testCaseId": "bf9e83b97e26e25e0d54585efea261be", "fullName": "test_api.TestWrongParameters#test_login_user_by_wrong_password", "labels": [{"name": "feature", "value": "Login user into the system  /user/login"}, {"name": "story", "value": "Выполняем вход пользователя с некорректным password"}, {"name": "tag", "value": "login_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "8876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}