{"name": "test_update_by_wrong_name", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 404", "trace": "self = <test_api.TestWrongParameters object at 0x0000015C50B62880>, add_one_user = <api_connector.ApiConnector object at 0x0000015C50B03220>, params = <class 'api_connector.ParamsReq'>\n\n    @allure.feature(\"Updated user /user/{username}\")\n    @allure.story('Обновляем пользователя с некорректным username')\n    @pytest.mark.update_user\n    def test_update_by_wrong_name(self, add_one_user, params):\n        \"\"\"updated user by wrong name\"\"\"\n        name = 'test_user'\n        z_id = 100\n        email = 'test@test.ru'\n        with allure.step(f\"Обновляем пользователя username={name}, id={z_id}, email={email}\"):\n            rez = add_one_user.update_user(name, params(id=z_id, email=email))\n        with allure.step(f\"Запрос отправлен, проверяем код ответа {rez[0]} == 404\"):\n>           assert rez[0] == 404, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 404\n\ntest_api.py:274: AssertionError"}, "description": "updated user by wrong name", "steps": [{"name": "Обновляем пользователя username=test_user, id=100, email=test@test.ru", "status": "passed", "steps": [{"name": "DELETE request to: https://petstore.swagger.io/v2/user/test_user", "status": "passed", "start": 1661536235481, "stop": 1661536235481}], "start": 1661536234865, "stop": 1661536235481}, {"name": "Запрос отправлен, проверяем код ответа 200 == 404", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 404\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 274, in test_update_by_wrong_name\n    assert rez[0] == 404, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661536235481, "stop": 1661536235481}], "start": 1661536234864, "stop": 1661536235482, "uuid": "c4337b1e-529c-4f16-8981-87f778ec4af7", "historyId": "abc83da211e5765ee1e6ddeebc6fa82a", "testCaseId": "a1d70af3f78850bcee4f422d425912cc", "fullName": "test_api.TestWrongParameters#test_update_by_wrong_name", "labels": [{"name": "story", "value": "Обновляем пользователя с некорректным username"}, {"name": "feature", "value": "Updated user /user/{username}"}, {"name": "tag", "value": "update_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "10216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}