{"name": "test_login_user_by_wrong_name", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Неверный код ответа, получен 200\nassert 200 == 400", "trace": "self = <test_api.TestWrongParameters object at 0x00000256CC29F1F0>, add_one_user = <api_connector.ApiConnector object at 0x00000256CC32ED30>\n\n    @allure.feature(\"Login user into the system  /user/login\")\n    @allure.story('Выполняем вход пользователя с некорректным username')\n    @pytest.mark.login_user\n    @pytest.mark.xfail\n    def test_login_user_by_wrong_name(self, add_one_user):\n        \"\"\"logged user by wrong name and correct password\"\"\"\n        rez = add_one_user.login_user(name='test1', password='12345')\n        with allure.step(\"Запрос отправлен, проверяем код ответа\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 400\n\ntest_api.py:243: AssertionError"}, "description": "logged user by wrong name and correct password", "steps": [{"name": "GET request to: https://petstore.swagger.io/v2/user/login", "status": "passed", "start": 1661532016285, "stop": 1661532016285}, {"name": "Запрос отправлен, проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 243, in test_login_user_by_wrong_name\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661532016285, "stop": 1661532016285}], "start": 1661532015636, "stop": 1661532016286, "uuid": "3d702da2-5c5c-46a8-9ce7-a2b5a27d4331", "historyId": "4f35d294161835c489a293a31e22869d", "testCaseId": "4c1d4e8712721e3395bdd7c94e567bbc", "fullName": "test_api.TestWrongParameters#test_login_user_by_wrong_name", "labels": [{"name": "story", "value": "Выполняем вход пользователя с некорректным username"}, {"name": "feature", "value": "Login user into the system  /user/login"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "login_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "16092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}